/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CapturaDigital.java
 *
 * Created on 20/01/2011, 18:35:18
 */
package epucjr.engyos.applet;

import epucjr.engyos.applet.controle.RegistradorDeDigital;
import epucjr.engyos.devicemanager.ControleBioDeviceHardware;
import javax.swing.JApplet;
import javax.swing.JOptionPane;

/**
 *
 * @author Rogerio
 */
public class CapturaDigital extends JApplet {

    /** Initializes the applet CapturaDigital */
    @Override
    public void init() {
        this.setSize(200, 240);
        /* try {
        java.awt.EventQueue.invokeAndWait(new Runnable() {

        public void run() {
        initComponents();

        }
        });
        } catch (Exception ex) {
        ex.printStackTrace();
        }
         *
         */
        ativarCapturaDigital();
    }

    public void ativarCapturaDigital() {
        RegistradorDeDigital registradorDeDigital = new RegistradorDeDigital();
        registradorDeDigital.capturarArmazenarDigitalServlet();

        JOptionPane.showMessageDialog(null, registradorDeDigital.getMensagemStatus());

        System.exit(0);
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFechar = new javax.swing.JButton();
        jPanel1 = new ImagePanel();

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar, java.awt.BorderLayout.SOUTH);
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButtonFecharActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}


