/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DigitalCaptureAppletGUI.java
 *
 * Created on 25/02/2011, 21:49:26
 */

package epucjr.engyos.applet.gui;

import epucjr.engyos.applet.worker.AcaoMarcarDigitalWorker;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import netscape.javascript.JSObject;

/**
 *
 * @author Rogerio
 */
public class DigitalCaptureAppletGUI extends javax.swing.JApplet {

    private AcaoMarcarDigitalWorker acaoMarcarDigitalWorker = null;
    private Informable informable = null;

    //Parametro da página passado através do parameter definido na carga do applet na página
    private String pageParameter;
    /** Initializes the applet DigitalCaptureAppletGUI */
    public void init() {
         pageParameter = getParameter("idReuniao");
//
        //this.paint(this.getGraphics());
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {//

                public void run() {
                     initComponents();
                   
                }
            });

            this.labelAviso.setText("");
            this.labelTitulo.setText("Inserção de digital");

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // The interface will update the text of the UI components
        informable = new Informable() {

            @Override
            public void messageChanged(String message) {
                //labelAviso.setText(message);
                publicarMensagemNaPaginaHtmlViaJavaScript(message);
            }
        };

     
       // ativarCapturaDeDigitalDevice(informable);

    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDeFundo = new javax.swing.JPanel();
        imagePanel = new ImagePanel(getCodeBase());
        labelTitulo = new javax.swing.JLabel();
        labelAviso = new javax.swing.JLabel();
        capturarDigitalButton = new javax.swing.JButton();

        painelDeFundo.setBackground(new java.awt.Color(231, 230, 230));
        //imagePanel.paint(this.getGraphics());

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        labelTitulo.setText("Por Favor Insira a digital");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelTitulo.setMaximumSize(new java.awt.Dimension(200, 14));
        labelTitulo.setMinimumSize(new java.awt.Dimension(200, 14));
        labelTitulo.setPreferredSize(new java.awt.Dimension(200, 14));

        labelAviso.setBackground(new java.awt.Color(255, 255, 255));
        labelAviso.setForeground(new java.awt.Color(255, 51, 51));
        labelAviso.setText("jLabel2");

        capturarDigitalButton.setText("Capturar");
        capturarDigitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturarDigitalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDeFundoLayout = new javax.swing.GroupLayout(painelDeFundo);
        painelDeFundo.setLayout(painelDeFundoLayout);
        painelDeFundoLayout.setHorizontalGroup(
            painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeFundoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capturarDigitalButton)
                    .addComponent(labelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelDeFundoLayout.setVerticalGroup(
            painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(labelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(capturarDigitalButton)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDeFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDeFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void capturarDigitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturarDigitalButtonActionPerformed
        if(informable != null){
            this.ativarCapturaDeDigitalDevice(this.informable, pageParameter);
            //System.out.println("ALWAYS");
        }
        else{
            //JOptionPane.showMessageDialog(null, "TIRED");
        }
    }//GEN-LAST:event_capturarDigitalButtonActionPerformed

    public void setMessage(String message){
        JOptionPane.showMessageDialog(null,"Mensagem: " + message + "\nidReuniao: " + pageParameter);
        System.exit(0);
    }

    public void ativarCapturaDeDigitalDevice(Informable informable, String idReuniao){        
        acaoMarcarDigitalWorker = new AcaoMarcarDigitalWorker(informable, idReuniao){

            @Override
            protected void done() {
                try {
                    String resposta = get();
                    labelAviso.setText(resposta);
                    publicarMensagemNaPaginaHtmlViaJavaScript(resposta);
                } catch (InterruptedException ex) {
                    //JOptionPane.showMessageDialog(null, "APPLET EXCEPTION:183:: " + ex.getMessage());
                    Logger.getLogger(DigitalCaptureAppletGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ExecutionException ex) {
                    //JOptionPane.showMessageDialog(null, "APPLET EXCEPTION:186:: " + ex.getMessage());
                    Logger.getLogger(DigitalCaptureAppletGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        };

        acaoMarcarDigitalWorker.execute();       
    }

    public void publicarMensagemNaPaginaHtmlViaJavaScript(String mensagem){
        try{
            JSObject jdJSObject = JSObject.getWindow(this);
            // dynamically change HTML in page; write data summary            
            jdJSObject.call("writeMessage", new Object[]{mensagem});
        }
        catch(netscape.javascript.JSException ex){
            //JOptionPane.showMessageDialog(null, "APPLET EXCEPTION204:: " + ex.getMessage());
            Logger.getLogger(DigitalCaptureAppletGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capturarDigitalButton;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel labelAviso;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelDeFundo;
    // End of variables declaration//GEN-END:variables

}
